# config_paths.yaml

# Reference genome
reference_genome: "/data/hamza/reference/barley_v3_split_2_parts.fa"

# Info file
info_file: "/home/hamzaamhal/snakemake_pipline/info_files"
variant_calling_list: "/home/hamzaamhal/variant_calling/Variant_calling_list.txt"

# Directories
bam_dir: "/data/hamza/mapping/output/bam_files"
flagstat_dir: "/data/hamza/mapping/output/flagstat"
index_dir: "/data/hamza/mapping/output/index"
idxstats_dir: "/data/hamza/mapping/output/idxstats"
output_dir_markdup: "/data/hamza/markduplicate/bam_dup1" #markduplicates output files
metrics_dir: "/data/hamza/markduplicate/metrics_files1" #metrics of markduplicates
# BWA tool path
bwa_path: "/home/contrera/soft/bwa-m2-2.0pre2_x64-linux/bwa-mem2"
GATK: "/home/contrera/soft/gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar"
# Number of threads
threads: 20

# Scripts
mapping_script: "/home/hamzaamhal/snakemake_pipline/scripts/mapping_sk.sh"
mark_duplicates_script: "/home/hamzaamhal/snakemake_pipline/scripts/02_mark_duplicates_sktest.sh"
# Done and log files
mapping_done: "/home/hamzaamhal/snakemake_pipline/output/mapping_done.txt"
mapping_output_log: "/home/hamzaamhal/snakemake_pipline/logfile/mapping_output.log"
mark_duplicates_done: "/home/hamzaamhal/snakemake_pipline/output/mark_duplicates_done.txt"
mark_duplicates_output_log: "/home/hamzaamhal/snakemake_pipline/logfile/mark_duplicates_output.log"
