# config_paths.yaml

# Reference genome
reference_genome: data/barley_test_7chr_60Mb_split.fa

#chr name list
CHROMOSOMES: # changed from mapping for names of chr
  - chr1H_part1
  - chr1H_part2
  - chr2H_part1
  - chr2H_part2
  - chr3H_part1
  - chr3H_part2
  - chr4H_part1
  - chr4H_part2
  - chr5H_part1
  - chr5H_part2
  - chr6H_part1
  - chr6H_part2
  - chr7H_part1
  - chr7H_part2

CHROMOSOMES_length:
  - name: chr1H
    size: 60000000
  - name: chr2H
    size: 60000000
  - name: chr3H
    size: 60000000
  - name: chr4H
    size: 60000000
  - name: chr5H
    size: 60000000
  - name: chr6H
    size: 60000000
  - name: chr7H
    size: 60000000


# Info file
#mapping
info_file: info_files/INFO_FILE_FINAL.txt # info file for mapping 
#
variant_calling_list: info_files/Variant_calling_list.txt
INTERVAL_LIST: info_files/interval2.list
SAMPLE_MAP: info_files/cohort.sample_map.list
BED_FILE: info_files/bedfile_fullchr.bed

# Directories
#mapping

bam_dir: results/mapping/bam_files
flagstat_dir: results/mapping/flagstat
index_dir: results/mapping/index
idxstats_dir: results/mapping/idxstats

#markdup

output_dir_markdup: results/markduplicate/bam_dup #markduplicates output files
metrics_dir: results/metrics_files #metrics of markduplicates


#single gvcf call

output_dir_singl_gvcf: results/gvcf_files # output dir for single gvcf

SequenceDictionary : data/SequenceDictionary.dict

#combine gvcf
COMBINED_GVCF_DIR: results/gvcf_files/combined_gvcf_file
TEMP_DIR: results/gvcf_files/temporal
FINAL_OUTPUT: results/gvcf_files/SBCC_combined.vcf
PER_CHR_OUTPUT_PREFIX: results/gvcf_files/gvcf_chr_file
VCF_WITH_MERGED_COORDS: results/gvcf_files/combined_mergedchromosomes_test.vcf
VCF_WITH_MERGED_COORDS_GZ: results/gvcf_files/combined_mergedchromosomes_test.vcf_test.gz
VCF_FINAL: results/gvcf_files/SBCC_combined_mergedchromosomes_final.vcf.gz
FILTERED_VCF: results/filtred_vcf/SBCC_vcf_filtred_dp_5_maf_0.05_missing_0.2_testsnakmake.vcf.gz
FILTRED_OUTPUT_DIR: results/filtred_vcf
fastq_input: data #modified quality  
quality_check_output: results/quality_check #modified quality
# BWA tool path
#bwa_path: "/home/contrera/soft/bwa-m2-2.0pre2_x64-linux/bwa-mem2"
# GATK Path
GATK: "/home/hamza/Automatized-Varaint-calling-and-haplotype-calling-SBCC-/gatk-4.6.0.0/gatk"
# Number of threads
threads: 20
threads_variantcall: 7






# Scripts
mapping_script: "scripts/02_mapping.sh"
mark_duplicates_script: "scripts/02_mark_duplicates_sktest.sh"
variant_calling_script: "scripts/03_variant_calling.single.gvcf.sh"
genotype_all_script: "scripts/05_genotype_all.sh"
COMBINE_CHR_SCRIPT: "scripts/06_combine_chr_update_cordinates.sh"
FILTER_VCF_SCRIPT: "scripts/07_filtervcffile.sh"
CHECK_QUALITY_SCRIPT: "scripts/01_check_quality.sh" # modified quality







# Done and log files
CHECK_QUALITY_DONE: "output/quality_check_done.txt" #modified quality
CHECK_QUALITY_LOG: "logfile/quality_check.log" #modified quality 
mapping_done: "output/mapping_done.txt"
mapping_output_log: "logfile/mapping_output.log"
mark_duplicates_done: "output/mark_duplicates_done.txt"
mark_duplicates_output_log: "logfile/mark_duplicates_output.log"
variant_calling_done: "output/variant_calling_done.txt"
variant_calling_log: "logfile/variant_calling_output.log"
genotype_all_output: "output/genotype_all_done.txt"
genotype_all_output_log: "logfile/genotype_all.log"
COMBINE_CHR_LOG: "logfile/06_combine_chr_update_cordinates.log"
COMBINE_CHR_DONE: "output/06_combine_chr_update_cordinates.done"
FILTER_VCF_LOG: "logfile/filter_vcf.log"
FILTER_VCF_DONE: "output/filter_vcf.done"

